[package]
name = "introsort"
version = "0.4.1"
authors = [ "Viktor Dahl <pazaconyoman@gmail.com>" ]
description = """
Fast sorting compatible with #[no_std].
Also has (optional) support for efficient and robust sorting of floating point numbers."""
keywords = ["sorting", "sort", "float"]
license = "Apache-2.0"
repository = "https://github.com/veddan/rust-introsort"
readme = "README.md"

[features]
default = [ "float" ]
float = ["num"]

[lib]
name = "introsort"
path = "src/lib.rs"
test = false
bench = false

[dependencies.num]
version = "*"
optional = true

[dev-dependencies]
rand = "0.3.7"

[profile.test]
opt-level = 1

